### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by KyleKing** [extractions/netrc#6]
Hi, thanks for building this action! We have found it to be very useful

I saw that you recently made changes to update for Node 16 support (https://github.com/extractions/netrc/commit/823ae2f13f3451082cf616eb6d4389ff6f5c6047) and I wondered if you could make a new tag release so that we could specify `@2` or continue using `@1`? We currently are using `@trunk` without any issues

**Comment by pawelaugustyn** [comment]
@rossmacarthur FYI
