### ISSUE TITLE
netrc info duplicated each CI run

### ISSUE THREAD

**Issue by sirnacnud** [extractions/netrc#7]
We ran in to an issue when running this action on the same physical machine, each time the action is invoked, the netrc info is appended to the existing netrc file, rather than replacing it. We only figured out this error when our password changed, but wasn't being picked up on the CI. Turns out our netrc file was `121K` of duplicated info.

The issue is caused by the file being opened in append mode.

**Comment by rossmacarthur** [comment]
Should be fixed by 2c3c152, released in v2
